const NAME_OR_PASSWORD_IS_REQUIRED = 'NAME_OR_PASSWORD_IS_REQUIRED'
const USER_DOES_NOT_EXISTS = 'USER_DOES_NOT_EXISTS'
const PASSWORD_ERROR = 'PASSWORD_ERROR'
const USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS'
const UNAUTHORIZATION = 'UNAUTHORIZATION'

export {
  NAME_OR_PASSWORD_IS_REQUIRED,
  USER_DOES_NOT_EXISTS,
  PASSWORD_ERROR,
  USER_ALREADY_EXISTS,
  UNAUTHORIZATION,
}
