const NAME_OR_PASSWORD_IS_REQUIRED = 'NAME_OR_PASSWORD_IS_REQUIRED'
const USER_DOES_NOT_EXISTS = 'USER_DOES_NOT_EXISTS'
const PASSWORD_ERROR = 'PASSWORD_ERROR'
const USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS'
const UNAUTHORIZATION = 'UNAUTHORIZATION'
const AUTHORIZATION_EXPIRES = 'AUTHORIZATION_EXPIRES'
const DATABASE_ERROR = 'DATABASE_ERROR'
const NO_PERMISSION = 'NO_PERMISSION'
const MISSING_PERAMATERS = 'MISSING_PERAMATERS'
const BAD_PARAMATERS = 'BAD_PARAMATERS'

export {
  BAD_PARAMATERS,
  DATABASE_ERROR,
  MISSING_PERAMATERS,
  NAME_OR_PASSWORD_IS_REQUIRED,
  NO_PERMISSION,
  PASSWORD_ERROR,
  UNAUTHORIZATION,
  AUTHORIZATION_EXPIRES,
  USER_ALREADY_EXISTS,
  USER_DOES_NOT_EXISTS
}
